version: '3.8'

services:
  pgpool:
    image: bitnami/pgpool:4.4.2
    container_name: pgpool
    restart: always
    environment:
      - PGPOOL_ADMIN_USERNAME=postgres
      - PGPOOL_ADMIN_PASSWORD=postgres
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=postgres
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=postgres
      - PGPOOL_BACKEND_NODES=0:192.168.57.101,1:192.168.57.102,2:192.168.57.103
    ports:
      - 15432:5432
