version: '3.8'

services:
  backend:
    image: foo_service
    volumes:
      - ./foo_service/components:/workspace/components
    restart: always

  nginx:
    image: nginx:1.22.1
    restart: always
    volumes:
      - ./nginx_conf/foo_service.conf:/etc/nginx/conf.d/foo_service.conf
    ports:
      - 7000:7000
    depends_on:
      - backend
