version: '3.8'

services:
  postgres:
    image: postgres:10.0-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS="--data-checksums"
    volumes:
      - /Study_Architecture/Replication/Postgresql/primary/postgresql.conf:/var/config/postgresql.conf
      - /Study_Architecture/Replication/Postgresql/primary/pg_hba.conf:/var/config/pg_hba.conf
      - /Study_Architecture/Replication/Postgresql/primary/init-script.sql:/scripts/init-script.sql
    command: >
      docker-entrypoint.sh
      -c config_file=/var/config/postgresql.conf
      -c hba_file=/var/config/pg_hba.conf
    ports:
      - 5432:5432
