version: '3.8'

services:
  redis1:
    image: redis:7.0
    ports:
      - 6380:6379

  redis2:
    image: redis:7.0
    ports:
      - 6381:6379

  redis3:
    image: redis:7.0
    ports:
      - 6382:6379
